package com.carevalojesus.pokeapi.util

object PokemonNames {

    const val SPRITE_BASE_URL =
        "https://raw.githubusercontent.com/PokeAPI/sprites/master/sprites/pokemon/other/official-artwork/"

    private val names = mapOf(
        1 to "Bulbasaur", 2 to "Ivysaur", 3 to "Venusaur",
        4 to "Charmander", 5 to "Charmeleon", 6 to "Charizard",
        7 to "Squirtle", 8 to "Wartortle", 9 to "Blastoise",
        10 to "Caterpie", 11 to "Metapod", 12 to "Butterfree",
        13 to "Weedle", 14 to "Kakuna", 15 to "Beedrill",
        16 to "Pidgey", 17 to "Pidgeotto", 18 to "Pidgeot",
        19 to "Rattata", 20 to "Raticate",
        21 to "Spearow", 22 to "Fearow",
        23 to "Ekans", 24 to "Arbok",
        25 to "Pikachu", 26 to "Raichu",
        27 to "Sandshrew", 28 to "Sandslash",
        29 to "Nidoran F", 30 to "Nidorina", 31 to "Nidoqueen",
        32 to "Nidoran M", 33 to "Nidorino", 34 to "Nidoking",
        35 to "Clefairy", 36 to "Clefable",
        37 to "Vulpix", 38 to "Ninetales",
        39 to "Jigglypuff", 40 to "Wigglytuff",
        41 to "Zubat", 42 to "Golbat",
        43 to "Oddish", 44 to "Gloom", 45 to "Vileplume",
        46 to "Paras", 47 to "Parasect",
        48 to "Venonat", 49 to "Venomoth",
        50 to "Diglett", 51 to "Dugtrio",
        52 to "Meowth", 53 to "Persian",
        54 to "Psyduck", 55 to "Golduck",
        56 to "Mankey", 57 to "Primeape",
        58 to "Growlithe", 59 to "Arcanine",
        60 to "Poliwag", 61 to "Poliwhirl", 62 to "Poliwrath",
        63 to "Abra", 64 to "Kadabra", 65 to "Alakazam",
        66 to "Machop", 67 to "Machoke", 68 to "Machamp",
        69 to "Bellsprout", 70 to "Weepinbell", 71 to "Victreebel",
        72 to "Tentacool", 73 to "Tentacruel",
        74 to "Geodude", 75 to "Graveler", 76 to "Golem",
        77 to "Ponyta", 78 to "Rapidash",
        79 to "Slowpoke", 80 to "Slowbro",
        81 to "Magnemite", 82 to "Magneton",
        83 to "Farfetch'd", 84 to "Doduo", 85 to "Dodrio",
        86 to "Seel", 87 to "Dewgong",
        88 to "Grimer", 89 to "Muk",
        90 to "Shellder", 91 to "Cloyster",
        92 to "Gastly", 93 to "Haunter", 94 to "Gengar",
        95 to "Onix",
        96 to "Drowzee", 97 to "Hypno",
        98 to "Krabby", 99 to "Kingler",
        100 to "Voltorb", 101 to "Electrode",
        102 to "Exeggcute", 103 to "Exeggutor",
        104 to "Cubone", 105 to "Marowak",
        106 to "Hitmonlee", 107 to "Hitmonchan",
        108 to "Lickitung",
        109 to "Koffing", 110 to "Weezing",
        111 to "Rhyhorn", 112 to "Rhydon",
        113 to "Chansey", 114 to "Tangela", 115 to "Kangaskhan",
        116 to "Horsea", 117 to "Seadra",
        118 to "Goldeen", 119 to "Seaking",
        120 to "Staryu", 121 to "Starmie",
        122 to "Mr. Mime", 123 to "Scyther",
        124 to "Jynx", 125 to "Electabuzz", 126 to "Magmar",
        127 to "Pinsir", 128 to "Tauros",
        129 to "Magikarp", 130 to "Gyarados",
        131 to "Lapras", 132 to "Ditto",
        133 to "Eevee",
        134 to "Vaporeon", 135 to "Jolteon", 136 to "Flareon",
        137 to "Porygon",
        138 to "Omanyte", 139 to "Omastar",
        140 to "Kabuto", 141 to "Kabutops",
        142 to "Aerodactyl", 143 to "Snorlax",
        144 to "Articuno", 145 to "Zapdos", 146 to "Moltres",
        147 to "Dratini", 148 to "Dragonair", 149 to "Dragonite",
        150 to "Mewtwo", 151 to "Mew"
    )

    fun getName(id: Int): String = names[id] ?: "Pokemon #$id"

    fun getImageUrl(id: Int): String = "${SPRITE_BASE_URL}$id.png"
}
